// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storms.Data;

#nullable disable

namespace storms.Migrations
{
    [DbContext(typeof(StormContext))]
    [Migration("20250929234320_ReworkStormModelUsingSingleDate")]
    partial class ReworkStormModelUsingSingleDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("storms.Models.Storm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LandfallDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxWindSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Storm");
                });
#pragma warning restore 612, 618
        }
    }
}
