// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storms.Data;

#nullable disable

namespace storms.Migrations
{
    [DbContext(typeof(StormContext))]
    partial class StormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("storms.Models.Storm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Basin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CycloneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLandfall")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LandfallDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxWindSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Storm");
                });
#pragma warning restore 612, 618
        }
    }
}
